/**
 * Permission constants matching backend permission names.
 *
 * Use these constants in permission checks instead of hardcoded strings
 * to prevent typos and enable IDE autocomplete.
 *
 * @example
 * ```tsx
 * const { hasPermission } = useAuth();
 * const canCreate = hasPermission(Permissions.EMPLOYEE_CREATE);
 * ```
 */
export const Permissions = {
  // Employee permissions
  EMPLOYEE_CREATE: 'EMPLOYEE_CREATE',
  EMPLOYEE_READ: 'EMPLOYEE_READ',
  EMPLOYEE_READ_TEAM: 'EMPLOYEE_READ_TEAM',
  EMPLOYEE_UPDATE: 'EMPLOYEE_UPDATE',
  EMPLOYEE_DELETE: 'EMPLOYEE_DELETE',

  // Time-off type permissions
  TIME_OFF_TYPE_CREATE: 'TIME_OFF_TYPE_CREATE',
  TIME_OFF_TYPE_READ: 'TIME_OFF_TYPE_READ',
  TIME_OFF_TYPE_UPDATE: 'TIME_OFF_TYPE_UPDATE',
  TIME_OFF_TYPE_DELETE: 'TIME_OFF_TYPE_DELETE',

  // Time-off request permissions
  TIME_OFF_REQUEST_CREATE: 'TIME_OFF_REQUEST_CREATE',
  TIME_OFF_REQUEST_READ_OWN: 'TIME_OFF_REQUEST_READ_OWN',
  TIME_OFF_REQUEST_READ_TEAM: 'TIME_OFF_REQUEST_READ_TEAM',
  TIME_OFF_REQUEST_READ_ALL: 'TIME_OFF_REQUEST_READ_ALL',
  TIME_OFF_REQUEST_APPROVE: 'TIME_OFF_REQUEST_APPROVE',

  // Time-off balance permissions
  TIME_OFF_BALANCE_READ_OWN: 'TIME_OFF_BALANCE_READ_OWN',
  TIME_OFF_BALANCE_READ_ALL: 'TIME_OFF_BALANCE_READ_ALL',
  TIME_OFF_BALANCE_ADJUST: 'TIME_OFF_BALANCE_ADJUST',

  // Timesheet permissions
  TIMESHEET_CREATE: 'TIMESHEET_CREATE',
  TIMESHEET_READ_OWN: 'TIMESHEET_READ_OWN',
  TIMESHEET_READ_TEAM: 'TIMESHEET_READ_TEAM',
  TIMESHEET_READ_ALL: 'TIMESHEET_READ_ALL',
  TIMESHEET_SUBMIT: 'TIMESHEET_SUBMIT',
  TIMESHEET_APPROVE: 'TIMESHEET_APPROVE',

  // Project permissions
  PROJECT_CREATE: 'PROJECT_CREATE',
  PROJECT_READ: 'PROJECT_READ',
  PROJECT_UPDATE: 'PROJECT_UPDATE',
  PROJECT_DELETE: 'PROJECT_DELETE',
  PROJECT_ASSIGN: 'PROJECT_ASSIGN',

  // Client permissions
  CLIENT_CREATE: 'CLIENT_CREATE',
  CLIENT_READ: 'CLIENT_READ',
  CLIENT_UPDATE: 'CLIENT_UPDATE',
  CLIENT_DELETE: 'CLIENT_DELETE',

  // Event permissions
  EVENT_CREATE: 'EVENT_CREATE',
  EVENT_READ: 'EVENT_READ',
  EVENT_UPDATE: 'EVENT_UPDATE',
  EVENT_DELETE: 'EVENT_DELETE',

  // Document permissions
  DOCUMENT_CREATE: 'DOCUMENT_CREATE',
  DOCUMENT_READ_OWN: 'DOCUMENT_READ_OWN',
  DOCUMENT_READ_ALL: 'DOCUMENT_READ_ALL',
  DOCUMENT_UPDATE: 'DOCUMENT_UPDATE',
  DOCUMENT_DELETE: 'DOCUMENT_DELETE',
  DOCUMENT_SHARE: 'DOCUMENT_SHARE',
  DOCUMENT_SIGN_OWN: 'DOCUMENT_SIGN_OWN',
  DOCUMENT_SIGN_READ: 'DOCUMENT_SIGN_READ',
  SHAREPOINT_BROWSE: 'SHAREPOINT_BROWSE',

  // Admin/Role permissions
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_READ: 'ROLE_READ',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',
  ROLE_ASSIGN: 'ROLE_ASSIGN',
} as const;

export type Permission = (typeof Permissions)[keyof typeof Permissions];
